### ISSUE TITLE
Cursed pumpkins

### ISSUE THREAD

**Issue by Timolino456** [MehVahdJukaar/modelfix-multi#2]
oh no
![image](https://user-images.githubusercontent.com/38137599/190849645-c7ce95eb-c7cb-41ab-a4b3-22efadba81bb.png)
Disabling your mod fixes this.

I tried going into my creative world and scrolling through the inventory to find other blocks that have this, but it seems like it only happens when they're actually placed.
My mod list is really large so I'm not sure wether giving you it is really helpful, but maybe you can make out a mod that definitely messes things up, so here you go anyway (I use PolyMC, so mods with .disbaled at the end are obviously disabled):
![image](https://user-images.githubusercontent.com/38137599/190849704-b4a9aed4-9b8a-412c-afe8-e3e6ed0247aa.png)

**Comment by MehVahdJukaar** [comment]
What mod are those blocks from?

**Comment by Timolino456** [comment]
They are normal vanilla pumpkins, grown from seeds.

**Comment by MehVahdJukaar** [comment]
You definitely have something that's messing with them as it doesnt happen in vanilla only. Its either a mod that modifies pumpkin or some visual or shader mod. Any idea?

**Comment by Timolino456** [comment]
I did some testing by disabling one block of mods after another (alphabetically, starting at A) and it stopped doing this when disabling Enhanced Block Entities. I then disabled almost every mod, keeping only EBE and Model Gap Fix enabled; the pumpkins still looked normal. I then enabled Sodium and Iris and then stuff looked like this (this is sand): 
![2022-09-18_14 49 35](https://user-images.githubusercontent.com/38137599/190902967-60614f50-19e1-47ff-83cc-1f846f0b9fce.png)
I then disabled Iris and everything looked normal again.
Maybe you can do something with this information?

**Comment by MehVahdJukaar** [comment]
Thanks I'll do some testing with those mods. If it was iris as I would have guessed I would expect it to have the same issues with other glow blocks like flowstone. Is that the case?

**Comment by Timolino456** [comment]
I honestly can't make out any specific pattern here. I just placed down the lower half of the creative inventory building blocks menu, here it seems to have issues with sand, red sandstone and parts of normal sandstone, red nether bricks and red terracotta (screenshot). Glowing blocks like sea lanterns, glowstone, pumpkin lanterns and normal lantern work fine.
It's also weird that in my first instance it was pumpkins, while they work fine with only those three mods enabled. It might not be a problem with specific blocks.
![2022-09-18_16 40 30](https://user-images.githubusercontent.com/38137599/190912735-0a49a79a-6c22-448d-b3b5-48dcd4d58e61.png)

**Comment by MehVahdJukaar** [comment]
So I've tryied replicating this myself but wasnt able to. I installed the mod, iris, and enhanced block entities and all blocks were displaying normally. This was on 1.18 btw. I did hot however test with an actual shaderpack on as I didnt have one. Does this only happen with a shaderpack on for you?

**Comment by Timolino456** [comment]
I've tested that already and no, that didn't change anything. But what I did find out is that certain resourcepacks seem to "activate" this issue. I do have multiple resourcepacks on top of one another (I did here too because I simply made a copy of the PolyMC instance). Both the latest version of Stay True and a custom Vanilla Tweaks pack seem to activate it. When removing all resource packs, the issue is gone. The affected blocks also change depending on what packs are active, although I'm not sure whether the block's texture actually has to be edited in any of the packs in order to be affected.
Removed only two packs which both changed one wooden planks texture (note how the sand looks different now):
![2022-09-19_19 03 18](https://user-images.githubusercontent.com/38137599/191073861-ae95dddf-d818-4fd8-bc9f-5ae2410b173b.png)
Removed everything but Vanilla Tweaks:
![2022-09-19_19 03 45](https://user-images.githubusercontent.com/38137599/191074369-9ebfd019-2b7a-4ec4-86ac-7f93af31d2e9.png)
Only Stay True enabled (I didn't have this one activated in any of the screenshots before):
![2022-09-19_19 05 50](https://user-images.githubusercontent.com/38137599/191074429-235c3bf1-a06a-40c6-b8d8-c5fd72d22f4c.png)
No resource packs enabled:
![2022-09-19_19 12 56](https://user-images.githubusercontent.com/38137599/191074664-01e0b3e0-ddb2-40e1-a26e-3f634afcc419.png)

**Comment by MehVahdJukaar** [comment]
What vanilla tweak pack are you using? I tried with stay true and it didn't do anything. Maybe it's something that happens when one has many texture packs? Could you try using just those 2 packs? Does it happen with only stay true aswell?

**Comment by Timolino456** [comment]
The third screenshot in my previous comment was with only Stay True. The Vanilla Tweaks pack is custom made, but it isn't really needed to cause it. It doesn't matter if I use both packs or just one of them, it happens as soon as I have at least one of them activated.
I also just tried to create a brand new PolyMC instance and redownloaded the mods and packs, but it didn't make any difference, still the same problem...

**Comment by MehVahdJukaar** [comment]
Damn that is so weird. Can you download texture dump mod and send me the texture Altas image it generates? I want to see if there is anything in common with the texture that have that issue

**Comment by Timolino456** [comment]
I would, but that's a Forge mod, isn't it? Can't really replicate the issue when using Forge since the Enhanced Block Entities mod doesn't have a Forge version and using Rubidium+Oculus alone doesn't trigger the issue. Or will it work anyway?

**Comment by MehVahdJukaar** [comment]
Oh sorry I thought it was on both loaders. Wack back to the drawing board I guess, I wish I could replicate this

**Comment by MehVahdJukaar** [comment]
Could you reload your texture pack and tell me which size texture atlases it created? (it should log that)

**Comment by Timolino456** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/38137599/192094360-863bb35a-b858-4775-9ee2-a8cf5ed704e4.png)

**Comment by MehVahdJukaar** [comment]
Yup Ty. I have published another version. I don't think it will fix anything tho

**Comment by Timolino456** [comment]
It worked lol (please ignore bad building skills)

Using 1.4:
![2022-09-24_16 31 18](https://user-images.githubusercontent.com/38137599/192103664-18ce343d-283f-42ed-888e-1d25a25ecd97.png)

Using 1.5:
![2022-09-24_16 29 52](https://user-images.githubusercontent.com/38137599/192103670-433fa820-98e8-43e6-a192-3d7e65648c03.png)

**Comment by MehVahdJukaar** [comment]
Unbelievable, blind fix worked o.o

**Comment by Timolino456** [comment]
Alright, this seems to be fixed. 1.5 is still missing on Modrinth though, btw.

**Comment by MehVahdJukaar** [comment]
Keeping up a mod on 2 websites is hard. I forgot

**Comment by Timolino456** [comment]
This bug seems to be back as of mod version 1.8. I just noticed that powered rails have the same kind of problem in my survival world, when disabling the mod it's normal again.

**Comment by MehVahdJukaar** [comment]
I know it's some kind of weird interaction with oculus (I think, that shaders mod)

**Comment by Timolino456** [comment]
Seems like this is a problem within Iris, not Model Gap Fix: ![image](https://user-images.githubusercontent.com/38137599/196039797-28623d71-9e62-45e3-ac1f-df7b7066e86e.png)

**Comment by MehVahdJukaar** [comment]
So glad to know they are aware of it and it's not something specific to this mos

**Comment by RaptaG** [comment]
Bug is fixed from Iris' side and it no longer appears. This should be closed.

**Comment by MehVahdJukaar** [comment]
Cool awesome
